version: '3'

services:
  spark-master:
    build: .
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
    volumes:
      - ./conf/master:/opt/spark/conf
      - ./data:/opt/spark/data

  spark-worker:
    build: .
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./conf/worker:/opt/spark/conf
      - ./data:/opt/spark/data